### ISSUE TITLE
multicolour_user sending migrate: alter in production environment

### ISSUE THREAD

**Issue by adam-cowley** [Multicolour/multicolour#102]
When I start the server in production mode, I receive the following error from Waterline:

```
Error: `migrate: "alter"` strategy is not supported in production, please change to `migrate: "safe"`.
    at module.exports [as migrateAlter] (/node_modules/multicolour/node_modules/waterline/lib/waterline/adapter/sync/strategies/alter.js:22:15)
    at Query.sync (/node_modules/multicolour/node_modules/waterline/lib/waterline/query/index.js:67:37)
    at /node_modules/multicolour/node_modules/waterline/lib/waterline.js:280:16
    at /node_modules/multicolour/node_modules/waterline/node_modules/async/lib/async.js:181:20
    at Immediate.iterate [as _onImmediate] (/node_modules/multicolour/node_modules/waterline/node_modules/async/lib/async.js:262:13)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```
After logging out `self.query.waterline.schema`, I can see that for some reason the multicolour_user model has the migration strategy set to alter.

```
multicolour_user: 
   { connection: 'production',
     identity: 'multicolour_user',
     tableName: 'multicolour_user',
     migrate: 'alter', // <-------
     attributes: 
      { username: [Object],
        email: [Object],
        name: [Object],
        role: [Object],
        salt: 'string',
        password: 'string',
        source: 'string',
        profile_image_url: [Object],
        requires_password: [Object],
        requires_email: [Object],
        id: [Object],
        createdAt: [Object],
        updatedAt: [Object] },
     meta: {} },
```

The output of user-model.js seems to have set the migrate property correctly so it must be overwritten somewhere.  I'm not sure whether this is a local quirk or something happening in Multicolour somewhere.

`NODE_ENV=production node app.js`
multicolour ^0.4.4
node v6.2.1

**Comment by davemackintosh** [comment]
Please ensure you have the latest version of Multicolour installed, this issue was resolved 2 days ago and published in 0.4.6 👍 

https://github.com/Multicolour/multicolour/commit/dd863cf1dd30eef7b582b0a865a811b751cc83ac
