### ISSUE TITLE
Windows CLI tool errors 

### ISSUE THREAD

**Issue by davemackintosh** [Multicolour/multicolour#198]
missing ) after arguments list

```
 SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Object.<anonymous> (C:\Users\ClientName\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainerFork.js:53:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
C:\uwamp\www\ProjectName\node_modules\.bin\multicolour:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
```

I think it's due to the way npm pushes `bin` scripts around as defined in the package.json

**Comment by davemackintosh** [comment]
This actually turns out to be an issue with bin files on Windows and PM2. Will revisit.
