### ISSUE TITLE
Error: Cannot find module 'waterline-sqlite3'

### ISSUE THREAD

**Issue by ShaneHudson** [Multicolour/multicolour#223]
### Versions

What is the output of:

1. `multicolour version` 0.6.6
2. `node -v` v7.8.0
3. `npm list --depth=0` 
```
├── hapi@16.1.1
├── joi@10.4.1
├── multicolour@0.6.6
├── multicolour-auth-oauth@1.2.3
├── multicolour-server-hapi@1.7.7
└── waterline-sqlite3@1.0.3 (git+https://github.com/newworldcode/sqlite3-adapter.git#be0db52330ee37f2e59d1a290744b1df80ef1084)
```

I needed to install hapi ^16.0.0 to remove errors:
```
npm ERR! peer dep missing: hapi@>=12.x.x, required by crumb@6.0.3
npm ERR! peer dep missing: hapi@^14.0.0 || ^15.0.0 || ^16.0.0, required by hapi-swagger@7.7.0
npm ERR! peer dep missing: hapi@>= 11, required by lout@9.2.0
```

### Expected behavior

Running `multicolour start` should run without errors.

### Actual behavior

```
module.js:472
    throw err;
    ^

Error: Cannot find module 'waterline-sqlite3'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/shanehudson/Development/Projects/NextLine/config.js:62:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

### Steps to reproduce behavior

Install multicolour, init project and run start.

### Things I tried
- Git cloning https://github.com/newworldcode/sqlite3-adapter
- Fixing missing dependencies (hapi)
- npm install a few times
- Using official adapter from npm
None of these things changed the could not find error.

**Comment by ShaneHudson** [comment]
This probably relates to #176.
