### ISSUE TITLE
Relating to the multicolour_model fails validation generation.

### ISSUE THREAD

**Issue by davemackintosh** [Multicolour/multicolour#237]
### Versions

What is the output of:

1. `multicolour version` 0.6.7
2. `node -v` All
3. `npm list --depth=0` All

### Expected behavior

Server starts

### Actual behavior

Server errors

```
/home/dave/www/node/foodex/API/node_modules/multicolour/lib/validator.js:92
              set_to.id = Joi.alternatives().try(Joi.number(), Joi.string()).optional()
                        ^

TypeError: Cannot set property 'id' of undefined
    at Object.keys.filter.forEach.attribute (/home/dave/www/node/foodex/API/node_modules/multicolour/lib/validator.js:92:25)
    at Array.forEach (native)
    at Object.keys.filter.forEach.collection_name (/home/dave/www/node/foodex/API/node_modules/multicolour/lib/validator.js:80:12)
    at Array.forEach (native)
    at Multicolour_Default_Validation.generate_schemas (/home/dave/www/node/foodex/API/node_modules/multicolour/lib/validator.js:72:8)
    at Array.forEach (native)
    at Multicolour_Default_Validation.register (/home/dave/www/node/foodex/API/node_modules/multicolour/lib/validator.js:119:11)
    at Map.use (/home/dave/www/node/foodex/API/node_modules/multicolour/index.js:243:12)
    at Map.start (/home/dave/www/node/foodex/API/node_modules/multicolour/index.js:259:10)
    at Object.<anonymous> (/home/dave/www/node/foodex/API/app.js:13:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```

### Steps to reproduce behavior

When relating to the `multicolour_user` model, the validator falls over.

**Comment by davemackintosh** [comment]
Turns out to be a non-issue and related to another bug. Suspected #238
