### ISSUE TITLE
Database connection fails with sails-mysql adapter

### ISSUE THREAD

**Issue by molovo** [Multicolour/multicolour#276]
### Versions

What is the output of:

1. `multicolour version` **0.6.10**
2. `node -v` **v8.1.3**
3. `npm list --depth=0`
```
api@1.0.0 /Users/molovo/projects/api
├── joi@10.6.0
├── multicolour@0.6.10
├── multicolour-hapi-jwt@0.1.4
├── multicolour-hapi-vantage@1.0.1
├── multicolour-seed@0.0.6
├── multicolour-server-hapi@1.7.8
├── sails-mysql@0.11.5
├── vantage-auth-basic@1.0.0 extraneous
└── waterline@0.12.2 extraneous

npm ERR! extraneous: vantage-auth-basic@1.0.0 /Users/molovo/projects/api/node_modules/vantage-auth-basic
npm ERR! extraneous: waterline@0.12.2 /Users/molovo/projects/api/node_modules/waterline
npm ERR! missing: waterline@git+https://github.com/Multicolour/waterline.git#0.12.x, required by multicolour@0.6.10
npm ERR! missing: vantage-auth-basic@latest, required by vantage@1.7.0
```

### Expected behavior

Server starts

### Actual behavior

```
Server started, go to http://localhost:1811/docs

undefined
/Users/molovo/projects/api/node_modules/sails-mysql/lib/adapter.js:396
        connection.query(_query.query, function(err, result) {
                   ^

TypeError: connection.query is not a function
    at __CREATE__ (/Users/molovo/projects/api/node_modules/sails-mysql/lib/adapter.js:396:20)
    at Object.create (/Users/molovo/projects/api/node_modules/sails-mysql/lib/adapter.js:363:9)
    at module.exports.create (/Users/molovo/.files/files/.config/yarn/global/node_modules/waterline/lib/waterline/adapter/dql.js:86:13)
    at child.createValues (/Users/molovo/.files/files/.config/yarn/global/node_modules/waterline/lib/waterline/query/dql/create.js:224:16)
    at /Users/molovo/.files/files/.config/yarn/global/node_modules/waterline/lib/waterline/query/dql/create.js:74:20
    at /Users/molovo/.files/files/.config/yarn/global/node_modules/async/lib/async.js:726:13
    at /Users/molovo/.files/files/.config/yarn/global/node_modules/async/lib/async.js:52:16
    at /Users/molovo/.files/files/.config/yarn/global/node_modules/async/lib/async.js:269:32
    at /Users/molovo/.files/files/.config/yarn/global/node_modules/async/lib/async.js:44:16
    at /Users/molovo/.files/files/.config/yarn/global/node_modules/async/lib/async.js:723:17
    at /Users/molovo/.files/files/.config/yarn/global/node_modules/async/lib/async.js:167:37
    at /Users/molovo/.files/files/.config/yarn/global/node_modules/async/lib/async.js:52:16
    at /Users/molovo/.files/files/.config/yarn/global/node_modules/async/lib/async.js:269:32
    at /Users/molovo/.files/files/.config/yarn/global/node_modules/async/lib/async.js:44:16
    at utils.hash_password (/Users/molovo/.files/files/.config/yarn/global/node_modules/multicolour/lib/user-model.js:33:9)
    at PBKDF2.crypto.pbkdf2 [as ondone] (/Users/molovo/.files/files/.config/yarn/global/node_modules/multicolour/lib/utils.js:38:5)
```

### Steps to reproduce behavior

Create new multicolour app with `multicolour init` and select MySQL or MariaDB for database. Error occurs on first startup.

**Comment by molovo** [comment]
I have a sneaking suspicion this is a `waterline` bug. Gonna try rolling back to `0.11.11` and see if that improves things.

**Comment by davemackintosh** [comment]
Hmm, yeah that looks like a Waterline bug. I'll try to reproduce locally. Thanks for reporting! :muscle:

**Comment by davemackintosh** [comment]
@molovo what's the content of your config.js? I don't see this issue locally.
