### ISSUE TITLE
500 on POST /user caused by incorrectly handled waterline validation error.

### ISSUE THREAD

**Issue by davemackintosh** [Multicolour/multicolour#29]
```bash
curl -i \
    -X POST \
    -H "Accept: application/vnd.api+json" \
    -H "Content-Type: application/json" \
    -H "Accept-Language: en-US;q=1.0" \
    -H "Accept-Encoding: gzip;q=1.0,compress;q=0.5" \
    -H "User-Agent: Context/co.context.Context (1005; OS Version 9.1 (Build 13B137))" \
    -d "{\"username\":\"abcd\",\"password\":\"efgh\",\"requires_email\":true,\"email\":\"my@email.com\",\"requires_password\":true,\"name\":\"abcd\"}" \
    "http://my.api/user"
```

```text
Debug: internal, implementation, error 
  TypeError: Uncaught error: Cannot read property '_attributes' of undefined
  at Object.get_association_keys (/app/node_modules/waterline-jsonapi/lib/utils.js:50:32)
  at JSONAPIModel (/app/node_modules/waterline-jsonapi/lib/data.js:40:29)
  at Object.JSONAPIModel [as create] (/app/node_modules/waterline-jsonapi/lib/data.js:19:12)
  at Function.generate_payload [as jsonapi] (/app/node_modules/multicolour-hapi-jsonapi/index.js:144:39)
  at Function.error_reply (/app/node_modules/multicolour-server-hapi/lib/handlers.js:43:44)
  at /app/node_modules/multicolour-server-hapi/lib/handlers.js:56:37
  at /app/node_modules/waterline/lib/waterline/query/dql/create.js:73:22
  at /app/node_modules/async/lib/async.js:708:13
  at /app/node_modules/async/lib/async.js:49:16
  at /app/node_modules/async/lib/async.js:258:21
  at /app/node_modules/async/lib/async.js:705:17
  at /app/node_modules/async/lib/async.js:40:16
  at /app/node_modules/waterline/lib/waterline/query/validate.js:71:22
  at /app/node_modules/async/lib/async.js:708:13
  at /app/node_modules/async/lib/async.js:49:16
  at /app/node_modules/async/lib/async.js:258:21
  at /app/node_modules/async/lib/async.js:705:17
  at /app/node_modules/async/lib/async.js:40:16
  at /app/node_modules/waterline/lib/waterline/query/validate.js:46:40
  at allValidationsChecked (/app/node_modules/waterline/lib/waterline/core/validations.js:210:5)
  at /app/node_modules/async/lib/async.js:49:16
  at done (/app/node_modules/async/lib/async.js:239:19)
  at /app/node_modules/async/lib/async.js:40:16
  at validate (/app/node_modules/waterline/lib/waterline/core/validations.js:152:76)
  at /app/node_modules/async/lib/async.js:162:20
  at /app/node_modules/async/lib/async.js:230:13
  at _arrayEach (/app/node_modules/async/lib/async.js:81:9)
  at _each (/app/node_modules/async/lib/async.js:72:13)
  at Object.async.forEachOf.async.eachOf (/app/node_modules/async/lib/async.js:229:9)
  at Object.async.forEach.async.each (/app/node_modules/async/lib/async.js:206:22)
  at Validator.validate (/app/node_modules/waterline/lib/waterline/core/validations.js:207:9)
  at /app/node_modules/waterline/lib/waterline/query/validate.js:42:25
  at /app/node_modules/async/lib/async.js:699:13
  at iterate (/app/node_modules/async/lib/async.js:256:13)
  at doNTCallback0 (node.js:428:9)
  at process._tickDomainCallback (node.js:398:13)
```

**Comment by davemackintosh** [comment]
While this is resolved, this is still relevant https://github.com/newworldcode/waterline-jsonapi/issues/1

**Comment by lluisgerard** [comment]
:+1:
