### ISSUE TITLE
Missed multicolour-auth-oauth module in CLI

### ISSUE THREAD

**Issue by Sogl** [Multicolour/multicolour#39]
Hi!

I'm from this wiki page:
https://github.com/Multicolour/multicolour/wiki/CLI

Just tried to build app with cli:
1. `npm i -g multicolour`
2. `multicolour init mult`:
```
? THIS WILL BASH YOUR CONFIG.JS AND PACKAGE.JSON, IF THEY EXIST. Continue? y
? Enter your project's name: mult
? What server technology would you like to use? hapi
? What database technology would you like to use? postgresql
? What authentication do you want for your API? 

      We've generated a few files for you and copied a few things around,
      This includes an app.js, config.js and a content/ folder. Please run
      "npm install ." to install all dependencies.

      Running node app.js will start running your server once dependencies are installed.
```
3. `cd mult && npm i` without errors.
4. `node app.js` or `npm start`:
```
module.js:339
    throw err;
    ^

Error: Cannot find module 'multicolour-auth-oauth'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/artyom/projects/mult/app.js:14:10)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

Fix:
1. `npm i multicolour-auth-oauth --save`
2. `node app.js`

**Comment by davemackintosh** [comment]
That's interesting, I'll investigate. Thanks for helping out.
