### ISSUE TITLE
Can't seed app generated with CLI

### ISSUE THREAD

**Issue by Sogl** [Multicolour/multicolour#42]
Hi!

I created an app with cli module, add seed module and after that it can't start:
```
sogl:tw artyom$ NODE_ENV=development node app.js
/Users/artyom/projects/tw/node_modules/waterline/lib/waterline/connections/index.js:52
      throw new Error(msg);
      ^

Error: Connection ("adapter") is missing a required property (`adapter`).  You should indicate the name of one of your adapters.
    at /Users/artyom/projects/tw/node_modules/waterline/lib/waterline/connections/index.js:52:13
    at Array.forEach (native)
    at _build (/Users/artyom/projects/tw/node_modules/waterline/lib/waterline/connections/index.js:44:24)
    at new module.exports (/Users/artyom/projects/tw/node_modules/waterline/lib/waterline/connections/index.js:23:8)
    at Waterline.initialize (/Users/artyom/projects/tw/node_modules/waterline/lib/waterline.js:101:22)
    at Multicolour_Waterline_Generator.start (/Users/artyom/projects/tw/node_modules/multicolour/lib/db.js:164:31)
    at multicolour.start (/Users/artyom/projects/tw/node_modules/multicolour/index.js:186:14)
    at Object.<anonymous> (/Users/artyom/projects/tw/app.js:23:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

What did I miss?

Repo with app:
https://github.com/Sogl/multicolour-tw

**Comment by davemackintosh** [comment]
https://github.com/Sogl/multicolour-tw/blob/master/config.js#L36

Was the config generated by the CLI or did you modify it? It's missing a connection name. It should be structured like this

```js
connections: {
  development: {
        adapter: "development",
        host: "localhost",
        port: 5432,
        user: 'postgres',
        password: '',
        database: "tw"
    }
}
```
